### ISSUE TITLE
What if AD does not reside in Azure AD, but in another cloud provider?

### ISSUE THREAD

**Issue by PatHat** [AzureADSamples/WebApp-WSFederation-DotNet#2]
Hello.

Can this app, which uses  the WS-Federation OWIN middleware  to simplify WS-Federation, be configured to federate authentication with an Active Directory other than Azure AD, e.g., an AD that resides in another cloud provider? Will this OWIN middleware allow it?

I'm afraid the answer may be no (but I hope I'm wrong!), based on the key called  "ida:AADInstance"  seen in Web.config, which seems to indicate this OIM middleware is geared to work only with Azure AD (AAD).

Please let me know your thought on this.

**Comment by dstrockis** [comment]
Hey PatHat... This middleware is designed should work with any identity provider that supports WS-Fed.  It's designed to work with the protocol, not just our own IDP. The naming of the keys in the web.config is a biproduct of the goal of this sample and our tooling in Visual Studio.
